apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: placeholder
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_HOST
              value: user-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              value: HS256
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DEFAULT_ADMIN_USERNAME
            - name: DEFAULT_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DEFAULT_ADMIN_EMAIL
            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DEFAULT_ADMIN_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: staging
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8000
      targetPort: http