grafana:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      uid: prometheus

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
